["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "contracts"

["protostar.contracts"]
pxl_erc721 = [
    "./contracts/pxls/PxlERC721/PxlERC721.cairo",
]
rtwrk_drawer = [
    "./contracts/pxls/RtwrkDrawer/RtwrkDrawer.cairo"
]
pxls_1_100 = [
    "./contracts/pxls/PxlERC721/pxls_metadata/pxls_1_100.cairo"
]
pxls_101_200 = [
    "./contracts/pxls/PxlERC721/pxls_metadata/pxls_101_200.cairo"
]
pxls_201_300 = [
    "./contracts/pxls/PxlERC721/pxls_metadata/pxls_201_300.cairo"
]
pxls_301_400 = [
    "./contracts/pxls/PxlERC721/pxls_metadata/pxls_301_400.cairo"
]

[profile.devnet.protostar.deploy]
gateway_url="http://127.0.0.1:5050/"
chain_id=1

[profile.testnet.protostar.deploy]
network="testnet"

[profile.mainnet.protostar.deploy]
network="mainnet"
