[project]
protostar-version = "0.8.1"

lib-path = "contracts"
cairo-path = ["contracts"]

[contracts]
proxy = [
    "./contracts/pxls/Proxy.cairo"
]
# pxls_1_100 = [
#     "./contracts/pxls/PxlERC721/pxls_metadata/pxls_1_100.cairo"
# ]
# pxls_101_200 = [
#     "./contracts/pxls/PxlERC721/pxls_metadata/pxls_101_200.cairo"
# ]
# pxls_201_300 = [
#     "./contracts/pxls/PxlERC721/pxls_metadata/pxls_201_300.cairo"
# ]
# pxls_301_400 = [
#     "./contracts/pxls/PxlERC721/pxls_metadata/pxls_301_400.cairo"
# ]
pxl_erc721 = [
    "./contracts/pxls/PxlERC721/PxlERC721.cairo",
]
rtwrk_drawer = [
    "./contracts/pxls/RtwrkDrawer/RtwrkDrawer.cairo"
]
rtwrk_erc721 = [
    "./contracts/pxls/RtwrkERC721/RtwrkERC721.cairo"
]
rtwrk_theme_auction = [
    "./contracts/pxls/RtwrkThemeAuction/RtwrkThemeAuction.cairo"
]

[profile.devnet.project]
gateway-url="http://127.0.0.1:5050/"
chain-id=1536727068981429685321

[profile.testnet.project]
network="testnet"
# Can't sign right now because argent wallet don't have the declare validate method yet
# account_address="0x03bc4F3912468951b3be911b9476177CC208dAe52Ae4F880540F4d24d3c61847"
# private_key_path="private/testnet.key"

[profile.mainnet.project]
network="mainnet"
